### ISSUE TITLE
Numeric data is parsed as decimal unconditionally

### ISSUE THREAD

**Issue by aiurovet** [damphat/json5-dart#12]
Thank you very much for your excellent JSON5 encoder/decoder, it works really well. One minor issue I spotted, but still would be nice if you could fix that or make it optional. Currently, the numeric data is parsed as decimal unconditionally. This causes an issue when I'm bluntly converting retrieved data to a string using .toString() and passing that as command-line argument width and height in pixels to an image conversion utility (an external executable). For my project, I'm converting all loaded data to strings anyway, so I'm easily handling the issue myself by using .toStringAsFixed(0) instead of .toString() whenever the need arises. But generally, it would be nice to have the feature out of the box if possible. Thank you.

**Comment by damphat** [comment]
You can use the `class JSON5Next` below.

- `JSON5Next.parse('100') ` would return an `int` instead of a `double`
- `JSON5Next.stringify(100)` would return "100" instead of "100.0"

Source code
```
import 'package:json5/json5.dart';

class JSON5Next {
  static dynamic _convert(dynamic obj) {
    const EPSILON = 0.0E-10;
    if (obj is double && obj.remainder(1) <= EPSILON) {
      return obj.toInt();
    } else if (obj is Map<String, dynamic>) {
      for (var key in obj.keys) {
        obj[key] = _convert(obj[key]);
      }
    } else if (obj is List<dynamic>) {
      for (var i = 0; i < obj.length; i++) {
        obj[i] = _convert(obj[i]);
      }
    }
    return obj;
  }

  static dynamic parse(String src) {
    return _convert(JSON5.parse(src));
  }

  static String stringify(dynamic obj, {dynamic space = 0}) {
    return JSON5.stringify(_convert(obj));
  }
}

void main() {
  var source = ''
      '{'
      '  name: "cat.jpg",  '
      '  width: 320,       '
      '  height: 240       '
      '}'
      '';

  // parser
  var size = JSON5Next.parse(source);

  // stringify again
  var str = JSON5Next.stringify(size);

  print(str); // SHOULD PRINT {width:320,height:240}
}
```

**Comment by aiurovet** [comment]
Thank you. As I said, this is not an issue for me, as I'm converting everything to string. I can easily identify those values, which are in fact, integers. I just thought that it would be nice to have such a feature out of the box, but this is not critical.
